language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0

install:
  - travis_retry composer self-update
  - travis_retry composer install --no-interaction --no-suggest

script:
  - vendor/bin/phpunit --coverage-clover=coverage.xml

after_success:
  - bash <(curl -s https://codecov.io/bash)

cache:
  directories:
    - $HOME/.composer/cache
